apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.fluentbit: |
    url: http://fluent-bit.argocd.svc.cluster.local:9880
    headers:
      - name: Content-Type
        value: application/json

  template.send-app-event: |
    webhook:
      fluentbit:
        method: POST
        path: /
        body: |
          {
            "app": "{{.app.metadata.name}}",
            "namespace": "{{.app.metadata.namespace}}",
            "syncStatus": "{{.app.status.sync.status}}",
            "healthStatus": "{{.app.status.health.status}}",
            "operationPhase": "{{.app.status.operationState.phase}}",
            "message": "{{.app.status.operationState.message}}",
            "startedAt": "{{.app.status.operationState.startedAt}}",
            "finishedAt": "{{.app.status.operationState.finishedAt}}"
          }

  trigger.on-sync-status-change: |
    - when: app.status.operationState.phase in ['Succeeded', 'Failed'] or app.status.sync.status != app.status.operationState.syncResult.status
      send: [send-app-event]
