apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: argocd
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*argocd*.log
        Parser            docker
        Tag               argocd.*
        Refresh_Interval  5
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               argocd.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        Annotations         Off

    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch.elastic-system.svc.cluster.local
        Port  9200
        Index argocd-logs
        Type  _doc
        Logstash_Format On
        Replace_Dots On

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
