apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: argocd
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    debug
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    @INCLUDE inputs.conf
    @INCLUDE filters.conf
    @INCLUDE outputs.conf

  inputs.conf: |
    [INPUT]
        Name        http
        Listen      0.0.0.0
        Port        9880
        Tag         argocd.webhook

  filters.conf: |
    [FILTER]
        Name                kubernetes
        Match               argocd.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        Merge_Log_Key       log
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name      parser
        Match     argocd.*
        Key_Name  log
        Parser    json

  outputs.conf: |
    [OUTPUT]
        Name            es
        Match           argocd.*
        Host            elasticsearch.elastic-system.svc.cluster.local
        Port            9200
        Index           argocd-logs
        Type            _doc
        Logstash_Format Off
        Replace_Dots    On
        Retry_Limit     False

    [OUTPUT]
        Name  stdout
        Match argocd.*

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
